from django.urls import path

from .vistas_mvt import (
    CategoriaCreateView,
    CategoriaDeleteView,
    CategoriaListView,
    CategoriaUpdateView,
    DashboardAdminView,
    DetalleReservaClienteView,
    MisReservasView,
    ReservaCreateAdminView,
    ReservaCreateClienteView,
    ReservaDeleteAdminView,
    ReservaDetailAdminView,
    ReservaListAdminView,
    ReservaUpdateAdminView,
    TarifaCreateView,
    TarifaDeleteView,
    TarifaListView,
    TarifaUpdateView,
    VehiculoCreateView,
    VehiculoDeleteView,
    VehiculoDetailView,
    VehiculoListView,
    VehiculoUpdateView,
)


urlpatterns = [
    path("admin/vehiculos/", VehiculoListView.as_view(), name="vehiculo_list"),
    path("admin/vehiculos/crear/", VehiculoCreateView.as_view(), name="vehiculo_create"),
    path("admin/vehiculos/<int:pk>/", VehiculoDetailView.as_view(), name="vehiculo_detail"),
    path("admin/vehiculos/<int:pk>/editar/", VehiculoUpdateView.as_view(), name="vehiculo_update"),
    path("admin/vehiculos/<int:pk>/eliminar/", VehiculoDeleteView.as_view(), name="vehiculo_delete"),
    path("admin/categorias/", CategoriaListView.as_view(), name="categoria_list"),
    path("admin/categorias/crear/", CategoriaCreateView.as_view(), name="categoria_create"),
    path("admin/categorias/<int:pk>/editar/", CategoriaUpdateView.as_view(), name="categoria_update"),
    path("admin/categorias/<int:pk>/eliminar/", CategoriaDeleteView.as_view(), name="categoria_delete"),
    path("admin/tarifas/", TarifaListView.as_view(), name="tarifa_list"),
    path("admin/tarifas/crear/", TarifaCreateView.as_view(), name="tarifa_create"),
    path("admin/tarifas/<int:pk>/editar/", TarifaUpdateView.as_view(), name="tarifa_update"),
    path("admin/tarifas/<int:pk>/eliminar/", TarifaDeleteView.as_view(), name="tarifa_delete"),
    path("admin/reservas/", ReservaListAdminView.as_view(), name="reserva_list_admin"),
    path("admin/reservas/crear/", ReservaCreateAdminView.as_view(), name="reserva_create_admin"),
    path("admin/reservas/<int:pk>/", ReservaDetailAdminView.as_view(), name="reserva_detail_admin"),
    path("admin/reservas/<int:pk>/editar/", ReservaUpdateAdminView.as_view(), name="reserva_update_admin"),
    path("admin/reservas/<int:pk>/eliminar/", ReservaDeleteAdminView.as_view(), name="reserva_delete_admin"),
    path("admin/dashboard/", DashboardAdminView.as_view(), name="dashboard_admin"),
    path("mis-reservas/", MisReservasView.as_view(), name="mis_reservas"),
    path("reservar/", ReservaCreateClienteView.as_view(), name="reserva_create"),
    path("reservas/<int:pk>/", DetalleReservaClienteView.as_view(), name="reserva_detail_cliente"),
]
